name: Flutter Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'

    - name: Install dependencies
      run: flutter pub get

    - name: Build for Windows
      run: flutter build windows

    - name: Build for macOS
      run: flutter build macos

    - name: Build for Linux
      run: flutter build linux

    - name: Create release
      run: |
        TAG_NAME=$(git describe --tags --abbrev=0)
        RELEASE_DIR="release/$TAG_NAME"
        mkdir -p $RELEASE_DIR
        cp build/windows/your_flutter_app.exe $RELEASE_DIR/your_flutter_app_$TAG_NAME.exe
        cp build/macos/your_flutter_app.app $RELEASE_DIR/your_flutter_app_$TAG_NAME.app
        cp -r build/linux/your_flutter_app $RELEASE_DIR/your_flutter_app_$TAG_NAME

    - name: Upload release
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release

