name: Flutter Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install dependencies
        run: flutter pub get

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux

      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
        shell: bash

      - name: Create release
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          RELEASE_DIR="release/$TAG_NAME/linux"
          mkdir -p $RELEASE_DIR
          cp -r build/linux/daily_plan $RELEASE_DIR/daily_plan_$TAG_NAME

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release

  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
        shell: bash

      - name: Create release
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          RELEASE_DIR="release/$TAG_NAME/windows"
          mkdir -p $RELEASE_DIR
          cp build/windows/daily_plan.exe $RELEASE_DIR/daily_plan_$TAG_NAME.exe

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release

  build_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install dependencies
        run: flutter pub get

      - name: Build for macOS
        run: flutter build macos

      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
        shell: bash

      - name: Create release
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          RELEASE_DIR="release/$TAG_NAME/macos"
          mkdir -p $RELEASE_DIR
          cp -r build/macos/daily_plan.app $RELEASE_DIR/daily_plan_$TAG_NAME.app

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release
